---
title: 胡荣的博客
SEOTitle: 胡荣的博客
header-img: https://cn.bing.com/th?id=OHR.PantheonParis_ZH-CN1546295756_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp
email: epsmail@126.com
description: 胡荣的个人博客, 分享个人经历
keyword: 开发, 后端, PHP, Java, 架构, 中间件
motto: 写写代码，吐吐苦水，睡睡懒觉
url: http://eps.ink
baseurl: /
cdnUrl: https://cdn.jsdelivr.net/gh/EPsheep/epsheep.github.io
timezone: Asia/Shanghai
encoding: utf-8
sidebar: true
sidebar-about-description: 凡世间一俗人尔
sidebar-avatar: https://s1.ax1x.com/2020/07/05/UpyY9A.jpg
RSS: false
weibo_username: "5857402266"
zhihu_username: jing-hao-75-45
github_username: EPsheep
netease_username: "328086810"
bilibili_username: "255717391"
friends:
- title: WDNMD
  href: https://chrischan13.github.io/wdnmd/
featured-tags: true
featured-condition-size: 1
highlighter: rouge
permalink: /posts/:title
paginate: 10
exclude:
- build
- css
- img
- js
- CNAME
- LICENSE
- package.json
- README.md
anchorjs: true
gems:
- jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
...
